import type { NextPage } from "next";
import Head from "next/head";
import Footer from "../components/Footer";
import HamburguerMenu from "../components/HamburguerMenu";
import Header from "../components/Header";

const Home: NextPage = () => {
  return (
    <div className="bg-gray-900 h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section id="hamburguer">
        <Header title="Menu" />
        <HamburguerMenu />
      </section>

      <Footer />
    </div>
  );
};

export default Home;
